server:
  port: 20002
eureka:
  instance:
    hostname: server2
  client:
#    register-with-eureka: false # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
#    fetch-registry: false   # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    service-url:
      defaultZone: http://zhy:zhy@server1:20001/eureka/,http://zhy:zhy@server3:20003/eureka/